### ISSUE TITLE
The specified value "#fff" does not conform to the required format

### ISSUE THREAD

**Issue by pdamoc** [cedricss/elm-css-systems#2]
Chrome has started throwing warnings if the colors are not specified with two-digit hexadecimal numbers. 

It looks like only `Css.Systems.Colors.black` and `Css.Systems.Colors.white` are throwing the warning.

**Comment by cedricss** [comment]
Hi! What is the Google Chrome error message? Isn't `#fff` supposed to be a valid value?
Cf https://www.w3.org/TR/css-color-3/#rgb-color :

> The format of an RGB value in hexadecimal notation is a ‘#’ immediately followed by either three or six hexadecimal characters. The three-digit RGB notation (#rgb) is converted into six-digit form (#rrggbb) by replicating digits, not by adding zeros. For example, #fb0 expands to #ffbb00. This ensures that white (#ffffff) can be specified with the short notation (#fff) and removes any dependencies on the color depth of the display.

**Comment by pdamoc** [comment]
Here is a screenshot with what I see in Chrome (Version 110.0.5481.77 ). 
![Screenshot 2023-02-08 at 08 28 34](https://user-images.githubusercontent.com/878106/217451857-e3efedf5-d29c-4c14-9171-ad290bddd264.png)

I also agree that `#fff` is a valid value so feel free to add a `wontfix` and close the PR too. The proposed change is considering that a lot of devs are looking at the console and this change would remove this noise. At the same time, it is also possible that Chrome would remove the warning in a future release.

**Comment by pdamoc** [comment]
Extra info: If you have `<input type="color" value="#fff">` it will show as black in both Chrome and Safari (Version 16.2 (18614.3.7.1.5)). 

`<input type="color" value="#ffffff">` will show as white in both.

**Comment by cedricss** [comment]
For the input type color, I would say this is another issue (and another spec), as the value of such input has to be a 7 characters long value: https://html.spec.whatwg.org/multipage/input.html#color-state-(type=color), and I guess you are not using an elm-css color for that, isn't it?

I've tried to reproduce the _"The specified value "#fff" does not conform to the required format."_ warning on my Chrome 110.0.5481.77, without luck: https://ellie-app.com/kXx323SGyKPa1 (no such warning on the console).

Do you have a minimal reproducible example? This issue is puzzling me :)

**Comment by pdamoc** [comment]
Sorry for the confusion, indeed the problem is related to using a `Color` field as an input for an `input [ type_ "color"`. 
Here is your ellie adapted to show the problem. You need to click the "click me" button in order to see the warning. I have no clue why it doesn't show out of the box. 
https://ellie-app.com/kXKsb9sMm5ba1

**Comment by cedricss** [comment]
Thanks for the MRE! I’ve published elm-css-systems 3.2.1 with your patch.
